# Generated by Django 5.0.1 on 2024-03-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditTrail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='asdasd',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
