# Generated by Django 5.0.1 on 2024-03-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuditTrail', '0002_auditlog_asdasd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='timestamp',
            new_name='_timestamp',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='asdasd',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='_action',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='_module',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='_name',
            field=models.CharField(default='asdasd', max_length=250),
            preserve_default=False,
        ),
    ]
