# Generated by Django 5.0.1 on 2024-03-13 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuditTrail', '0004_alter_auditlog__timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='_action',
            new_name='audit_action',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='_module',
            new_name='audit_module',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='_name',
            new_name='audit_name',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='_timestamp',
            new_name='audit_timestamp',
        ),
    ]
