# Generated by Django 5.0.1 on 2024-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('customer', 'Customer')], max_length=10, null=True),
        ),
    ]
