# Generated by Django 5.0.1 on 2024-01-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(choices=[(1, 'Active'), (0, 'Inactive')], default=True),
        ),
    ]
