# Generated by Django 5.0.1 on 2024-01-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=10, null=True),
        ),
    ]
