# Generated by Django 5.0.1 on 2024-04-19 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('label', models.TextField(choices=[('tips', 'Tips'), ('guides', 'Guides')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TGimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='tips_guides')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipguide')),
            ],
        ),
    ]
