# Generated by Django 5.0.1 on 2024-04-08 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_alter_products_id'),
        ('Shop', '0002_featuredproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
    ]
