# Generated by Django 5.0.1 on 2024-04-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=250)),
                ('gcash', models.CharField(max_length=50)),
                ('facebook_url', models.URLField()),
                ('phone_number', models.CharField(max_length=50)),
                ('gcash_insta_pay', models.ImageField(null=True, upload_to='screenshot')),
            ],
        ),
    ]
