# Generated by Django 5.0.1 on 2024-04-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_shopdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='email',
            field=models.EmailField(default='brandalbuz@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
