# Generated by Django 5.0.1 on 2024-02-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointOfSale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('change', models.DecimalField(decimal_places=2, max_digits=9, null='True')),
                ('date_occured', models.DateField(auto_now_add=True)),
                ('cashier', models.CharField(max_length=50)),
            ],
        ),
    ]
