# Generated by Django 5.0.1 on 2024-02-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointOfSale', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gcash_num',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
