# Generated by Django 5.0.1 on 2024-03-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PointOfSale', '0009_alter_cart_product_id_alter_item_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_occured',
            field=models.DateField(auto_now=True),
        ),
    ]
