# Generated by Django 5.0.1 on 2024-01-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(max_length=40, unique=True)),
                ('sub_category', models.CharField(max_length=40, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=1)),
                ('t_img', models.ImageField(default='lz_fishing.jpg', upload_to='products')),
                ('date_registered', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
