# Generated by Django 5.0.1 on 2024-01-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('fish', 'Fish'), ('aquarium supplies', 'Aquarium Supplies'), ('fish food', 'Fish Food')], max_length=40, unique=True),
        ),
    ]
