# Generated by Django 5.0.1 on 2024-01-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_t_img_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('fish', 'Fish'), ('aquarium supplies', 'Aquarium Supplies'), ('fish food', 'Fish Food')], max_length=40),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_category',
            field=models.CharField(max_length=40),
        ),
    ]
