# Generated by Django 5.0.1 on 2024-01-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_products_category_alter_products_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='current_stocks',
            new_name='initial_stocks',
        ),
    ]
