# Generated by Django 5.0.1 on 2024-01-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_rename_current_stocks_products_initial_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='initial_stocks',
            new_name='stocks',
        ),
        
    ]
