# Generated by Django 5.0.1 on 2024-02-04 10:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_rename_initial_stocks_products_stocks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StocksLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stocks_added', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(editable=False, max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.products')),
            ],
        ),
    ]
