# Generated by Django 5.0.1 on 2024-02-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_stockslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockslog',
            old_name='product_id',
            new_name='product_name',
        ),
    ]
