# Generated by Django 5.0.1 on 2024-02-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_rename_product_id_stockslog_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockslog',
            name='added_by',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockslog',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
