# Generated by Django 5.0.1 on 2024-02-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_stockslog_added_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockslog',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
