# Generated by Django 5.0.1 on 2024-02-04 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_rename_product_name_stockslog_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockslog',
            name='added_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockslog',
            name='product_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockslog',
            name='stocks_added',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stockslog',
            name='supplier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockslog',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
