# Generated by Django 5.0.1 on 2024-02-04 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_stockslog_added_by_alter_stockslog_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockslog',
            name='stocks_added',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='stockslog',
            name='supplier',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockslog',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
