# Generated by Django 5.0.1 on 2024-02-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_alter_stockslog_stocks_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockslog',
            name='stocks_added',
            field=models.PositiveIntegerField(),
        ),
    ]
