# Generated by Django 5.0.1 on 2024-03-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_supplier_alter_stockslog_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
