# Generated by Django 5.0.1 on 2024-03-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0017_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
